version: "3"
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: instagram
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - ./db:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    phpfpm:
        image: bitnami/php-fpm:7.2-debian-10
        ports:
            - 9000:9000
        volumes:
            - ./app:/usr/share/nginx/html
            - ./php/php.ini:/opt/bitnami/php/etc/php.ini
    nginx:
        image: nginx:1.16.1-alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./app:/usr/share/nginx/html
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx/logs/:/var/log/nginx/